AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambdas-scheduler

  Sample SAM Template for lambdas-scheduler

Globals:
  Function:
    Timeout: 300
    MemorySize: 5000
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  ChicagoBudgetLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-function-1/
      Handler: app.chicagoBudgetUpload
      Runtime: python3.10
      Architectures:
        - x86_64

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
      Tags: 
       - Key: "resource"
         Value: "demo"

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
      Tags: 
        - Key: "resource"
          Value: "demo"

#Outputs:
  # Define your desired outputs here if you need any
  # Example:
  # MyOutputValue:
  #   Description: Some description of the output value.
  #   Value: !GetAtt MyResourceName.Arn
